---
name: venv-update-ci
on: push
jobs:
  tox:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: true
      matrix:
        toxenv:
          - lint
          - py36
          - py27
          - pypy
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - run: pip install tox==3.21.2
      - run: pip install -r CI/requirements.txt
      - run: sudo apt-get install -y pypy pypy-dev
      - run: tox -e ${{ matrix.toxenv }}
